configure fully and start testing

diff --git a/.github/workflows/sdk_publish.yaml b/.github/workflows/sdk_publish.yaml
--- a/.github/workflows/sdk_publish.yaml
+++ b/.github/workflows/sdk_publish.yaml
@@ -14,13 +14,43 @@ on:
   workflow_dispatch: {}
 jobs:
   publish:
-    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
-    with:
-      target: my-first-target
-    secrets:
-      github_access_token: ${{ secrets.GITHUB_TOKEN }}
-      java_gpg_passphrase: ${{ secrets.JAVA_GPG_PASSPHRASE }}
-      java_gpg_secret_key: ${{ secrets.JAVA_GPG_SECRET_KEY }}
-      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
-      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
-      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
+    runs-on: ubuntu-latest
+    env:
+      sonatype_passphrase: ${{ secrets.SONATYPE_PASSPHRASE }}
+      sonatype_secret_key: ${{ secrets.SONATYPE_SECRET_KEY }}
+      sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
+      sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: '11'
+          cache: 'gradle'
+
+      - name: Verify Config
+        run: |
+          ./gradlew jreleaserConfig
+
+      - name: Clean Project
+        run: |
+          ./gradlew clean
+
+      - name: Stage Artifact
+        run: |
+          ./gradlew publish
+
+      - name: Full Release
+        run: |
+          ./gradlew jreleaserFullRelease --dry-run
+
+      - name: Check Status
+        run: |
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "Error occurred during publishing"
+            exit $STATUS
+          fi
